import os
import sys

import streamlit as st

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.ui import setup, badge

setup("Phase 1 - Segmentation", "\U0001F9E9")
ASSETS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets")

st.title("Phase 1 · Defect segmentation")
badge("REAL RESULTS", "real")
st.caption(
    "nnU-Net v2, 2-D, single-channel 16-bit PNG input, two classes "
    "(background, pore/flaw). RTX 3050 4 GB VRAM, patch 768×768, batch 1, "
    "nnUNetTrainer_200epochs, 5-fold cross-validation."
)

c1, c2, c3, c4 = st.columns(4)
c1.metric("Dice (5-fold mean)", "0.805")
c2.metric("Precision", "0.862")
c3.metric("Recall", "0.841")
c4.metric("IoU", "0.709")

st.divider()
col1, col2 = st.columns(2)
with col1:
    st.subheader("Per-fold Dice")
    p = os.path.join(ASSETS, "fig2_fold_dice_bar.png")
    if os.path.exists(p):
        st.image(p, width='stretch')
    st.caption("Folds: 0.804, 0.794, 0.796, 0.825, 0.808 — consistent across folds, "
              "no single fold dominating the mean.")
with col2:
    st.subheader("Metrics summary")
    p = os.path.join(ASSETS, "fig4_metrics_bar.png")
    if os.path.exists(p):
        st.image(p, width='stretch')

st.divider()
st.subheader("Held-out test: defect size transfer")
st.metric("R², predicted vs. Snow reference √area (held-out cylinders)", "0.986")
st.caption(
    "The network's governing-defect size on the 14 held-out cylinders correlates "
    "strongly with Snow's own Laplacian-of-Gaussian reference labels — the model "
    "is reproducing a validated segmentation method on unseen data, which is the "
    "honest framing this project uses rather than claiming ground truth."
)

st.divider()
st.markdown(
    "**Train / test split.** Stratified by process regime (nominal / high-VED / "
    "spatter-seeded) and by fatigue stress level (300 MPa HCF / 450 MPa LCF), "
    "so both classes appear in train and test. ~40 training cylinders, ~20 held out."
)
st.markdown(
    "**Labels.** Algorithmically generated by Snow's Laplacian-of-Gaussian + "
    "thresholding + clustering pipeline, not human-annotated — the model learns "
    "to reproduce that published method on unseen cylinders."
)
