import plotly.graph_objects as go
import streamlit as st

from src.data import STUDY_METRICS, FOLD_DICE, HELDOUT_SIZE_R2
from src.ui import badge

ACCENT = "#B5473A"
GREY = "#8A9096"


def render():
    st.title("Phase 1 · Defect segmentation")
    badge("REAL RESULTS", "real")
    st.caption(
        "nnU-Net v2, 2-D, single-channel 16-bit PNG input, two classes "
        "(background, pore/flaw). RTX 3050 4 GB VRAM, patch 768×768, batch 1, "
        "nnUNetTrainer_200epochs, 5-fold cross-validation."
    )

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Dice (5-fold mean)", f"{STUDY_METRICS['Dice']:.3f}")
    c2.metric("Precision", f"{STUDY_METRICS['Precision']:.3f}")
    c3.metric("Recall", f"{STUDY_METRICS['Recall']:.3f}")
    c4.metric("IoU", f"{STUDY_METRICS['IoU']:.3f}")

    st.divider()
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Dice by fold")
        mean = sum(FOLD_DICE) / len(FOLD_DICE)
        folds = [f"fold {i}" for i in range(len(FOLD_DICE))]
        fig = go.Figure(go.Bar(x=folds, y=FOLD_DICE, marker_color=GREY))
        fig.add_hline(y=mean, line_dash="dash", line_color=ACCENT,
                      annotation_text=f"mean {mean:.3f}", annotation_position="top left")
        fig.update_layout(yaxis_range=[0.75, 0.85], yaxis_title="Dice",
                          height=340, margin=dict(t=20, b=10))
        st.plotly_chart(fig, width='stretch')
        st.caption("Consistent across folds — no single fold dominates the mean.")
    with col2:
        st.subheader("Metrics summary")
        names = list(STUDY_METRICS.keys())
        vals = list(STUDY_METRICS.values())
        fig = go.Figure(go.Bar(x=names, y=vals, marker_color=ACCENT))
        fig.update_layout(yaxis_range=[0, 1], height=340, margin=dict(t=20, b=10))
        st.plotly_chart(fig, width='stretch')

    st.divider()
    st.subheader("Held-out test: defect size transfer")
    st.metric("R², predicted vs. Snow reference √area (14 held-out cylinders)",
              f"{HELDOUT_SIZE_R2:.3f}")
    st.caption(
        "The network's governing-defect size on the held-out cylinders correlates "
        "strongly with Snow's own Laplacian-of-Gaussian reference labels — the "
        "model is reproducing a validated segmentation method on unseen data, "
        "which is the honest framing this project uses rather than claiming "
        "ground truth."
    )

    st.divider()
    st.markdown(
        "**Train / test split.** Stratified by process regime (nominal / high-VED "
        "/ spatter-seeded) and by fatigue stress level (300 MPa HCF / 450 MPa "
        "LCF), so both classes appear in train and test. ~40 training cylinders, "
        "~20 held out."
    )
    st.markdown(
        "**Labels.** Algorithmically generated by Snow's Laplacian-of-Gaussian + "
        "thresholding + clustering pipeline, not human-annotated — the model "
        "learns to reproduce that published method on unseen cylinders."
    )
